"""LangGraph nodes for the document generation skill."""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Mapping

from jinja2 import Environment, FileSystemLoader, StrictUndefined

logger = logging.getLogger(__name__)


class DocumentGenerationError(Exception):
    """Base exception for document generation failures."""

    pass


class ProfileLoadError(DocumentGenerationError):
    """Raised when candidate profile data cannot be loaded."""

    pass


class ApprovedMatchesNotFoundError(DocumentGenerationError):
    """Raised when no approved matches exist for document generation."""

    pass


class TemplateRenderError(DocumentGenerationError):
    """Raised when Jinja2 template rendering fails."""

    pass


from src.ai.generate_documents.contracts import (
    CVExperienceInjection,
    DocumentDeltas,
    GeneratedDocuments,
    MotivationLetterDeltas,
    TextReviewAssistEnvelope,
)
from src.ai.generate_documents.prompt import (
    build_generate_documents_prompt,
    SYSTEM_PROMPT,
)
from src.ai.generate_documents.review import build_deterministic_indicators
from src.ai.generate_documents.storage import DocumentArtifactStore
from src.ai.match_skill.storage import MatchArtifactStore
from src.shared.log_tags import LogTag


def create_studio_graph():
    """Create a graph for LangGraph Studio."""
    from langgraph.graph import StateGraph, END
    from typing import TypedDict

    class GenerateDocumentsState(TypedDict):
        source: str
        job_id: str
        requirements: list[Any]
        profile_base_data: dict[str, Any]
        review_payload: dict[str, Any]
        artifact_refs: dict[str, Any]
        status: str

    chain = build_default_generate_documents_chain()
    store = DocumentArtifactStore()
    node = _make_generate_documents_node(
        chain,
        store=store,
        match_store=MatchArtifactStore(store.root),
    )

    graph = StateGraph(GenerateDocumentsState)
    graph.add_node("generate_documents", node)
    graph.set_entry_point("generate_documents")
    graph.add_edge("generate_documents", END)

    return graph.compile()


def build_default_generate_documents_chain(model: Any | None = None) -> Any:
    """Build the standard LangChain-native generation chain with structured output."""
    from langchain_core.prompts import ChatPromptTemplate
    from langchain_google_genai import ChatGoogleGenerativeAI

    # We use ChatPromptTemplate with system/user placeholders
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "{system}"),
            ("user", "{user}"),
        ]
    )

    model_name = "gemini-2.5-flash"
    if not os.environ.get("GOOGLE_API_KEY"):
        # We fall back to a demo chain if no credentials are present
        return _make_demo_generate_documents_chain()

    chat_model = model or ChatGoogleGenerativeAI(model=model_name)
    return prompt | chat_model.with_structured_output(DocumentDeltas)


def _make_demo_generate_documents_chain() -> Any:
    """Mock chain producing static DocumentDeltas for local Studio usage."""

    class DemoChain:
        def invoke(self, inputs: dict[str, str]) -> DocumentDeltas:
            return DocumentDeltas(
                cv_summary="This is a demo CV summary generated by the fallback chain.",
                cv_injections=[
                    CVExperienceInjection(
                        experience_id="EXP001",
                        new_bullets=["Added this bullet via the demo generator."],
                    )
                ],
                letter_deltas=MotivationLetterDeltas(
                    subject_line="Demo Application",
                    intro_paragraph="I am applying via the demo mode of the LangGraph pipeline.",
                    core_argument_paragraph="My demo experience makes me a perfect fit for this mock role.",
                    alignment_paragraph="I am excited to join the demo institution.",
                    closing_paragraph="Thank you for viewing this demo output.",
                ),
                email_body="Please find my demo application attached.",
            )

    return DemoChain()


def _default_profile_base_data() -> dict[str, Any]:
    """Return a minimal profile payload that satisfies the document templates."""

    return {
        "owner": {
            "full_name": "Demo Candidate",
            "contact": {
                "phone": "+00 000 0000",
                "email": "demo@example.com",
                "addresses": [{"value": "Demo Street 1"}],
            },
            "links": {"linkedin": "https://linkedin.com/in/demo-candidate"},
        },
        "cv_generation_context": {"tagline_seed": "Applied AI and software systems"},
        "experience": [],
        "education": [],
        "publications": [],
        "languages": [],
        "skills": {
            "programming_languages": [],
            "ml_ai": [],
            "data_platforms": [],
            "orchestration_devops": [],
            "electronics_robotics": [],
        },
    }


def generate_documents_bundle(
    *,
    source: str,
    job_id: str,
    chain: Any,
    profile_base: dict[str, Any],
    approved_matches_raw: list[dict[str, Any]],
    requirements_raw: list[dict[str, Any]],
    review_items: list[dict[str, Any]],
    approved_state_hash: str,
    state: Mapping[str, Any],
) -> tuple[DocumentDeltas, GeneratedDocuments, TextReviewAssistEnvelope]:
    """Generate document payloads from in-memory primitive inputs only."""

    req_lookup = {
        item["id"]: item["text"]
        for item in requirements_raw
        if "id" in item and "text" in item
    }
    enriched_matches = [
        {
            **match,
            "requirement_text": req_lookup.get(
                match.get("requirement_id"), "Unknown Requirement"
            ),
        }
        for match in approved_matches_raw
    ]

    logger.info(f"{LogTag.LLM} Building prompt and invoking document generator")
    prompt = build_generate_documents_prompt(
        profile_base=profile_base,
        approved_matches=enriched_matches,
        review_items=review_items,
    )
    deltas: DocumentDeltas = chain.invoke({"system": SYSTEM_PROMPT, "user": prompt})
    logger.info(
        f"{LogTag.LLM} Generated document deltas for {source}/{job_id}: cv_injections={len(deltas.cv_injections)}"
    )

    logger.info(f"{LogTag.FAST} Building deterministic review indicators")
    indicators = build_deterministic_indicators(deltas)
    review_assist = TextReviewAssistEnvelope(
        job_id=job_id,
        source_state_hash=approved_state_hash,
        indicators=indicators,
        summary=(
            f"Found {len(indicators)} deterministic warnings"
            if indicators
            else "Clean output"
        ),
    )

    logger.info(f"{LogTag.FAST} Rendering markdown documents")
    rendered = _render_documents_internal(profile_base, deltas, state)
    return deltas, rendered, review_assist


def _load_generation_inputs_from_disk(
    state: Mapping[str, Any],
    artifact_store: DocumentArtifactStore,
    match_store: MatchArtifactStore,
) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]], str]:
    """Load profile, requirements, approved matches, and hash from storage."""

    source = state.get("source")
    job_id = state.get("job_id")
    approved_path = match_store.job_root(source, job_id) / "approved" / "state.json"
    if not approved_path.exists():
        logger.error(f"{LogTag.FAIL} Approved matches not found at {approved_path}")
        raise ApprovedMatchesNotFoundError(
            f"No approved matches found for {source}/{job_id}. "
            "Run match_skill and approve matches first."
        )

    profile_base, requirements_raw, approved_matches_raw, source_hash = (
        artifact_store.load_generation_inputs(
            source=source,
            job_id=job_id,
            match_store=match_store,
            profile_base_data=state.get("profile_base_data"),
            requirements=state.get("requirements") or [],
        )
    )

    if not profile_base:
        logger.warning(f"{LogTag.WARN} Profile base data not found in state or file")
        profile_base = _default_profile_base_data()
    return profile_base, requirements_raw, approved_matches_raw, source_hash


def _persist_generation_outputs_to_store(
    *,
    artifact_store: DocumentArtifactStore,
    source: str,
    job_id: str,
    deltas: DocumentDeltas,
    rendered: GeneratedDocuments,
    review_assist: TextReviewAssistEnvelope,
) -> dict[str, str]:
    """Persist generated document artifacts using the module store."""

    return artifact_store.write_document_payload(
        source=source,
        job_id=job_id,
        deltas=deltas,
        rendered=rendered,
        review_assist=review_assist,
    )


def _make_generate_documents_node(
    chain: Any,
    *,
    store: DocumentArtifactStore,
    match_store: MatchArtifactStore,
    final_status: str = "documents_generated",
    load_inputs: Callable[
        [Mapping[str, Any]],
        tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]], str],
    ]
    | None = None,
    persist_outputs: Callable[
        [str, str, DocumentDeltas, GeneratedDocuments, TextReviewAssistEnvelope],
        dict[str, str],
    ]
    | None = None,
):
    """Factory for the document generation node."""

    artifact_store = store
    approved_match_store = match_store

    def _current_loader(
        current_state: Mapping[str, Any],
    ) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]], str]:
        if load_inputs is not None:
            return load_inputs(current_state)
        return _load_generation_inputs_from_disk(
            current_state,
            artifact_store,
            approved_match_store,
        )

    def _current_persist(
        out_source: str,
        out_job_id: str,
        out_deltas: DocumentDeltas,
        out_rendered: GeneratedDocuments,
        out_review: TextReviewAssistEnvelope,
    ) -> dict[str, str]:
        if persist_outputs is not None:
            return persist_outputs(
                out_source,
                out_job_id,
                out_deltas,
                out_rendered,
                out_review,
            )
        return _persist_generation_outputs_to_store(
            artifact_store=artifact_store,
            source=out_source,
            job_id=out_job_id,
            deltas=out_deltas,
            rendered=out_rendered,
            review_assist=out_review,
        )

    def generate_documents_node(state: Mapping[str, Any]) -> dict[str, Any]:
        """Generate tailored application documents based on approved matches.

        Steps: load profile → load approved matches → build prompt → invoke
        LLM chain → run deterministic review indicators → render Jinja2
        templates → persist artifacts.

        Args:
            state: LangGraph state mapping containing at minimum ``source``
                and ``job_id``. Optionally ``profile_base_data``,
                ``requirements``, ``review_payload``, and context overrides
                (``city``, ``receiver_name``, etc.).

        Returns:
            Dict with keys ``document_deltas``, ``generated_documents``,
            ``artifact_refs`` (merged), and ``status`` set to
            ``"documents_generated"``.

        Raises:
            ProfileLoadError: If the profile JSON is missing or malformed.
            ApprovedMatchesNotFoundError: If no approved matches exist on disk.
            TemplateRenderError: If Jinja2 template rendering fails.
        """

        source = state.get("source")
        job_id = state.get("job_id")
        review_items = (state.get("review_payload") or {}).get("items", [])

        logger.info(f"{LogTag.FAST} Starting document generation for {source}/{job_id}")

        profile_base, requirements_raw, approved_matches_raw, source_hash = (
            _current_loader(state)
        )

        deltas, rendered, review_assist = generate_documents_bundle(
            source=source,
            job_id=job_id,
            chain=chain,
            profile_base=profile_base,
            approved_matches_raw=approved_matches_raw,
            requirements_raw=requirements_raw,
            review_items=review_items,
            approved_state_hash=source_hash,
            state=state,
        )

        refs = _current_persist(source, job_id, deltas, rendered, review_assist)

        artifact_refs = dict(state.get("artifact_refs") or {})
        artifact_refs.update(refs)

        logger.info(f"{LogTag.OK} Document generation complete")
        return {
            "document_deltas": deltas.model_dump(),
            "generated_documents": rendered.model_dump(),
            "artifact_refs": artifact_refs,
            "status": final_status,
        }

    return generate_documents_node


def _render_documents_internal(
    profile_base: dict[str, Any],
    deltas: DocumentDeltas,
    state: Mapping[str, Any],
) -> GeneratedDocuments:
    """Render Jinja2 templates into Markdown strings for each document type.

    Loads templates from ``src/generate_documents/templates/`` using
    ``StrictUndefined`` so missing variables fail loudly. Context keys
    ``city``, ``receiver_name``, ``receiver_department``, and
    ``receiver_institution`` are read from ``state`` when present, otherwise
    sensible defaults are used.

    Args:
        profile_base: Candidate base profile dict passed directly to templates.
        deltas: Structured LLM output containing CV summary, injections,
            letter deltas, and email body.
        state: LangGraph state mapping; read-only — used only for context
            overrides.

    Returns:
        ``GeneratedDocuments`` with ``cv_markdown``, ``letter_markdown``, and
        ``email_markdown`` populated.

    Raises:
        TemplateRenderError: If any Jinja2 template fails to render.
    """

    template_root = Path(__file__).parent / "templates"
    env = Environment(
        loader=FileSystemLoader(str(template_root)),
        undefined=StrictUndefined,
        autoescape=False,
    )

    # Generic context for the templates
    context = {
        "profile": profile_base,
        "document_deltas": deltas.model_dump(),
        "current_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "city": "Berlin",  # Default if not in state
        "receiver_name": "Hiring Committee",
        "receiver_department": "Hiring Team",
        "receiver_institution": "Institution",
    }

    # Override context if present in state
    overrides = ("city", "receiver_name", "receiver_department", "receiver_institution")
    for key in overrides:
        if value := state.get(key):
            context[key] = value

    try:
        cv_markdown = env.get_template("cv_template.jinja2").render(**context)
        letter_markdown = env.get_template("cover_letter_template.jinja2").render(
            **context
        )
        email_markdown = env.get_template("email_template.jinja2").render(**context)
    except Exception as exc:
        logger.error(f"{LogTag.FAIL} Template rendering failed: {exc}")
        raise TemplateRenderError(f"Failed to render templates: {exc}") from exc

    return GeneratedDocuments(
        cv_markdown=cv_markdown,
        letter_markdown=letter_markdown,
        email_markdown=email_markdown,
    )
